(function(g){var window=this;var wva=function(a,b){return g.Jb(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.G)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.an(a.w,b,c)},xva=function(a,b){var c=[];
g.jk(b,function(d){try{var e=g.fo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.eo(e)&&c.push(d)},a);
return c},yva=function(a,b){var c=xva(a,b);
(0,g.y)(c,function(d){g.fo.prototype.remove.call(this,d)},a)},zva=function(a){if(a.Uc){if(a.Uc.locationOverrideToken)return{locationOverrideToken:a.Uc.locationOverrideToken};
if(null!=a.Uc.latitudeE7&&null!=a.Uc.longitudeE7)return{latitudeE7:a.Uc.latitudeE7,longitudeE7:a.Uc.longitudeE7}}return null},Ava=function(a,b){g.bb(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},Bva=function(a,b){var c=b instanceof g.uc?b:g.yc(b,/^data:image\//i.test(b));
a.src=g.vc(c)},b6=function(){},Cva=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Dva=function(a){if(a.Id&&"function"==typeof a.Id)return a.Id();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Fb(a)},Eva=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Ae&&"function"==typeof a.Ae)var c=a.Ae();else if(a.Id&&"function"==typeof a.Id)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Gb(a);d=Dva(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Fva=function(a,b,c,d){var e=new g.Pm(null,void 0);
a&&g.Qm(e,a);b&&g.Rm(e,b);c&&g.Sm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Qo[a]=!0;
var c=g.Oo();c&&c.publish.apply(c,arguments);g.Qo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Mm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Gva(this,a.capabilities||""),Hva(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Gva=function(a,b){a.capabilities.clear();
(0,g.we)(b.split(","),g.Sa(wva,Iva)).forEach(function(c){a.capabilities.add(c)})},Hva=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Jva=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Kva=function(a){return new e6(a)},Lva=function(a){return g.Ma(a)?(0,g.Ec)(a,Kva):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ma(a)?"["+(0,g.Ec)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Mva=function(a){return(0,g.Ec)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.Za(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.Za(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Fs)(),c=(0,g.Es)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Nva=function(){var a=(0,g.Es)();
a&&yva(a,a.o.ag(!0))},m6=function(){var a=g.Hs("yt-remote-connected-devices")||[];
g.sb(a);return a},Ova=function(a){if(g.cb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Ec)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Pva=function(a){g.Gs("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Hs("yt-remote-device-id");a||(a=i6(),g.Gs("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.bb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.bb(a,b);g.Is()&&g.ub(a,b);a=Ova(a);if(g.cb(a))try{g.Sq("remote_sid")}catch(c){}else try{g.Qq("remote_sid",a.join(","),-1)}catch(c){}},Qva=function(){return g.Hs("yt-remote-session-browser-channel")},Rva=function(){return g.Hs("yt-remote-local-screens")||[]},Sva=function(){g.Gs("yt-remote-lounge-token-expiration",!0,86400)},Tva=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Ec)(Rva(),function(d){return d.loungeToken}),c=(0,g.Ec)(a,function(d){return d.loungeToken});
(0,g.vi)(c,function(d){return!g.bb(b,d)})&&Sva();
g.Gs("yt-remote-local-screens",a,31536E3)},Uva=function(a,b){g.Gs("yt-remote-session-browser-channel",a);
g.Gs("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.bb(c,d)||c.push(d);Pva(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.fb(a,o6());Pva(a)},Vva=function(){if(!r6){var a=g.po();
a&&(r6=new g.Zn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Wva=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Xva=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Yva(a.shift(),function(){s6(a)}):t6()},Zva=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Yva=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Xva();
a&&a(!1,"No cast extension found")},awa=function(){if($va){var a=2,b=Xva(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Yva("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},bwa=function(){awa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.Ed=b;this.B=(0,g.x)(this.mF,this);this.o=!1;this.u=0;this.w=this.Ea=null;this.A=[]},v6=function(a,b,c){g.A.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.Ed=b;this.u=(0,g.x)(this.nF,this);this.o=[]},w6=function(a){a.Ea=g.Vf(a.u,a.Ed);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Cva(a)},y6=function(){},z6=function(){},cwa=function(){},ewa=function(a){return(a=dwa(a))?new ActiveXObject(a):new XMLHttpRequest},dwa=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.I1(this);this.u=new g.Uf;this.u.setInterval(250)},gwa=function(a,b,c){a.uj=1;
a.Ug=Z5(b.clone());a.Pi=c;a.C=!0;fwa(a,null)},B6=function(a,b,c,d,e){a.uj=1;
a.Ug=Z5(b.clone());a.Pi=null;a.C=c;e&&(a.QB=!1);fwa(a,d)},fwa=function(a,b){a.fk=(0,g.G)();
C6(a);a.Jh=a.Ug.clone();$5(a.Jh,"t",a.F);a.Km=0;a.Nc=a.o.Yq(a.o.Am()?b:null);0<a.Mr&&(a.xp=new v6((0,g.x)(a.NC,a,a.Nc),a.Mr));a.A.ia(a.Nc,"readystatechange",a.dO);var c=a.ti?g.Pb(a.ti):{};a.Pi?(a.eq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Nc.send(a.Jh,a.eq,a.Pi,c)):(a.eq="GET",a.QB&&!g.le&&(c.Connection="close"),a.Nc.send(a.Jh,a.eq,null,c));a.o.ff(1)},jwa=function(a,b,c){for(var d=!0;!a.Zh&&a.Km<c.length;){var e=hwa(a,c);
if(e==D6){4==b&&(a.jh=4,E6(15),d=!1);break}else if(e==iwa){a.jh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.jh=1,E6(17),d=!1);a.gf=a.gf&&d;d||(G6(a),H6(a))},hwa=function(a,b){var c=a.Km,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return iwa;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Km=d+c;return e},lwa=function(a,b){a.fk=(0,g.G)();
C6(a);var c=b?window.location.hostname:"";a.Jh=a.Ug.clone();Y5(a.Jh,"DOMAIN",c);Y5(a.Jh,"t",a.F);try{a.mf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.jh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in kwa)k=I6[l]=kwa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Yc(g.Yb("b/12014412"),d+"</body></html>");a.mf.open();a.mf.write(g.Tc(c));a.mf.close();a.mf.parentWindow.m=(0,g.x)(a.xN,a);a.mf.parentWindow.d=(0,g.x)(a.YA,a,!0);a.mf.parentWindow.rpcClose=(0,g.x)(a.YA,a,!1);c=a.mf.createElement("DIV");a.mf.parentWindow.document.body.appendChild(c);d=g.xc(a.Jh.toString());d=g.fd(g.vc(d));d=g.Yc(g.Yb("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Zc(c,d);a.o.ff(1)},C6=function(a){a.Pu=(0,g.G)()+a.B;
mwa(a,a.B)},mwa=function(a,b){if(null!=a.xk)throw Error("WatchDog timer not null");
a.xk=J6((0,g.x)(a.FN,a),b)},K6=function(a){a.xk&&(g.v.clearTimeout(a.xk),a.xk=null)},H6=function(a){a.o.tx()||a.Zh||a.o.co(a)},G6=function(a){K6(a);
g.Je(a.xp);a.xp=null;a.u.stop();g.xqa(a.A);if(a.Nc){var b=a.Nc;a.Nc=null;b.abort();b.dispose()}a.mf&&(a.mf=null)},F6=function(a,b){try{a.o.QA(a,b),a.o.ff(4)}catch(c){}},owa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;nwa(a,b,function(k){k?c(!0):g.v.setTimeout(function(){owa(a,b,c,d,f)},f)})}},nwa=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Bva(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},pwa=function(a){this.o=a;
this.u=new y6},qwa=function(a){var b=M6(a.o,a.Fk,"/mail/images/cleardot.gif");
Z5(b);owa(b.toString(),5E3,(0,g.x)(a.gE,a),3,2E3);a.ff(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Yd=new A6(a,void 0,void 0,void 0),a.Yd.ti=a.Kr,b=a.o,b=M6(b,b.Am()?a.ll:null,a.Lr),E6(5),!g.je||g.Nd(10))$5(b,"TYPE","xmlhttp"),B6(a.Yd,b,!1,a.ll,!1);else{$5(b,"TYPE","html");var c=a.Yd;a=!!a.ll;c.uj=3;c.Ug=Z5(b.clone());lwa(c,a)}},P6=function(a){g.jf.call(this);
this.headers=new g.Mm;this.S=a||null;this.w=!1;this.V=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.aa=this.G=this.U=!1;this.F=0;this.J=null;this.ea="";this.N=this.Z=!1},rwa=function(a){return g.je&&g.Md(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},swa=function(a){return"content-type"==a.toLowerCase()},uwa=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;twa(a);Q6(a)},twa=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},wwa=function(a){if(a.w&&"undefined"!=typeof g.N1)if(a.V[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.Vf(a.MA,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.pd(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!vwa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";twa(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){xwa(a);
var c=a.o,d=a.V[0]?g.Ja:null;a.o=null;a.V=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},xwa=function(a){a.o&&a.N&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},ywa=function(a,b){this.o=a;
this.map=b;this.context=null},zwa=function(a){g.Le.call(this,"statevent",a)},Awa=function(a,b){g.Le.call(this,"timingevent",a);
this.size=b},Bwa=function(a){g.Le.call(this,"serverreachability",a)},Ewa=function(a){Cwa(a);
if(3==a.o){var b=a.Zl++,c=a.Pn.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.uj=2;b.Ug=Z5(c.clone());Bva(new Image,b.Ug.toString());b.fk=(0,g.G)();C6(b)}Dwa(a)},Fwa=function(a){a.FE(1,0);
a.Pn=M6(a,null,a.Jr);W6(a)},Cwa=function(a){a.Yg&&(a.Yg.abort(),a.Yg=null);
a.qc&&(a.qc.cancel(),a.qc=null);a.dg&&(g.v.clearTimeout(a.dg),a.dg=null);X6(a);a.Pd&&(a.Pd.cancel(),a.Pd=null);a.dh&&(g.v.clearTimeout(a.dh),a.dh=null)},Gwa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new ywa(a.SJ++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Pd||a.dh||(a.dh=J6((0,g.x)(a.XA,a),0),a.nj=0)},Iwa=function(a,b){if(1==a.o){if(!b){a.Zl=Math.floor(1E5*Math.random());
var c=a.Zl++,d=new A6(a,"",c,void 0);d.ti=null;var e=Y6(a),f=a.Pn.clone();Y5(f,"RID",c);Y5(f,"CVER","1");V6(a,f);gwa(d,f,e);a.Pd=d;a.o=2}}else 3==a.o&&(b?Hwa(a,b):0==a.u.length||a.Pd||Hwa(a))},Hwa=function(a,b){if(b)if(6<a.ai){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.Zl-1;var d=Y6(a)}else c=b.G,d=b.Pi;else c=a.Zl++,d=Y6(a);var e=a.Pn.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.Hj);V6(a,e);c=new A6(a,a.w,c,a.nj+1);c.ti=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Pd=c;gwa(c,e,d)},V6=function(a,b){if(a.Ad){var c=a.Ad.Rw();
c&&g.zb(c,function(d,e){Y5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.ai&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.ai?e:f-d;try{g.zb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Jwa=function(a){a.qc||a.dg||(a.F=1,a.dg=J6((0,g.x)(a.WA,a),0),a.gj=0)},Z6=function(a){if(a.qc||a.dg||3<=a.gj)return!1;
a.F++;a.dg=J6((0,g.x)(a.WA,a),Kwa(a,a.gj));a.gj++;return!0},N6=function(a,b,c){a.bq=c;
a.yf=b.sg;a.C||Fwa(a)},X6=function(a){null!=a.ii&&(g.v.clearTimeout(a.ii),a.ii=null)},Kwa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Ad&&(c=null);var d=(0,g.x)(a.PO,a);c||(c=new g.Pm("//www.google.com/images/cleardot.gif"),Z5(c));nwa(c.toString(),1E4,d)}else E6(2);Lwa(a,b)},Lwa=function(a,b){a.o=0;
a.Ad&&a.Ad.gw(b);Dwa(a);Cwa(a)},Dwa=function(a){a.o=0;
a.yf=-1;if(a.Ad)if(0==a.A.length&&0==a.u.length)a.Ad.Qq();else{g.jb(a.A);var b=g.jb(a.u);a.A.length=0;a.u.length=0;a.Ad.Qq(b)}},M6=function(a,b,c){var d=g.Xm(c);
if(""!=d.o)b&&g.Rm(d,b+"."+d.o),g.Sm(d,d.A);else{var e=window.location;d=Fva(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Uk&&g.zb(a.Uk,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.ai);V6(a,d);return d},J6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new zwa(a7,a))},Mwa=function(){},Nwa=function(){this.o=[];
this.u=[]},Owa=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.H(this.nN,0,this);g.C(this,this.o);this.Ed=5E3;this.u=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Yn;this.u=new b7(this.rO,this);this.o=null;this.wb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.N=c||!1},Pwa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.bq,sessionId:a.o.w,arrayId:a.o.Hj}},Qwa=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Iwa(a.o),Ewa(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Rwa=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.pd(4,a))||"";b&&(this.port=":"+b);this.domain=g.qd(a)||"";a=g.Lc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.qc(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Ad(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.A,d,!0),onError:g.Sa(a.w,e),Vd:g.Sa(a.B,e)};c&&(a.vb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Iq(b,a)},Vwa=function(){var a=Swa;
Twa();h7.push(a);Uwa(h7)},i7=function(a,b){Twa();
var c=h7,d=Wwa(a,String(b));g.cb(c)?Xwa(d):(Uwa(c),(0,g.y)(c,function(e){e(d)}))},Twa=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",h7,void 0))},Xwa=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Uwa=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Wwa=function(a,b){var c=((0,g.G)()-Ywa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.P.call(this);
this.F=a;this.o=[]},Zwa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},$wa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.we)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Zwa(a,b[d])||c;return c},axa=function(a,b){var c=a.o.length;
a.o=(0,g.we)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.P.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Ea=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},bxa=function(a){if(a.o.length){var b=(0,g.Ec)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.xF,a),(0,g.x)(a.wF,a))}},o7=function(a){var b=Lva(Rva());
b=(0,g.we)(b,function(c){return!c.uuid});
return $wa(a,b)},q7=function(a,b){Tva((0,g.Ec)(a.o,Jva));
b&&Sva()},s7=function(a,b){g.P.call(this);
this.C=b;var c=g.Hs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.bb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Lk(this.o))},cxa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Gb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Lk(a.o)),a.o=b,a.P("screenChange"));dxa(a)},u7=function(a){isNaN(a.w)||g.No(a.w);
a.w=g.Lo((0,g.x)(a.gu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},exa=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Tb("Requesting availability of screen w/o lounge token.")});
return b},dxa=function(a){a=g.Gb(g.Ab(a.o,function(b){return b}));
g.sb(a);a.length?g.Gs("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};fxa(this)},hxa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.me();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);cxa(a.u,l,function(m){e(m?l:null)})}else c?gxa(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));cxa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},ixa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},gxa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={vb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Iq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},jxa=function(a){a.o=a.w.me();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},fxa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.GF,a));jxa(a);a.A=Lva(g.Hs("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.me,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.P("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Gs("yt-remote-automatic-screen-cache",(0,g.Ec)(a.A,Jva)));x7(a);a.B[b.uuid]=b.id;g.Gs("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Hs("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.P.call(this);
this.V=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.V,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.zP,this);this.B=(0,g.x)(this.NN,this);this.A=g.Lo((0,g.x)(function(){kxa(this,null)},this),12E4)},lxa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Lk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Lk(b))},kxa=function(a,b){g.No(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.lp,a),d=(0,g.x)(a.pe,a);a.lx(b,c,d,5)}}else a.pe(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.S=c;this.B=null;this.F=g.Ja;this.C=NaN;this.N=(0,g.x)(this.CP,this);this.o=g.Ja},mxa=function(a){a.o=a.H.TC(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.lp(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.pe(b)},a))},nxa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.S;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Vva()&&(b.env_useStageMdx=1);return g.yd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Lo((0,g.x)(this.Ij,this,null),150)},D7=function(a,b,c,d){g.P.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.vM,this)},oxa=function(a,b){return b?g.Za(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Swa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.Je(a.o),(a.o=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.u):a.P("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.VA,a,b)),b.w?a.P("yt-remote-cast2-session-change",b.w):c&&a.o.Ij(null)):a.P("yt-remote-cast2-session-change",null))},pxa=function(a){var b=a.u.SC(),c=a.o&&a.o.u;
a=(0,g.Ec)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=oxa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},vxa=function(a,b,c,d,e,f,k){qxa()?rxa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?sxa(a,c):(window.__onGCastApiAvailable=function(l,m){l?sxa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),txa(),c(!1))},d?g.Xo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?bwa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(awa(),s6(uxa.map(Zva))))):H7("Cannot initialize because not running Chrome")},txa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);wxa(!1);g.To(M7);M7.length=0},N7=function(){return!!g.Hs("yt-remote-cast-installed")},xxa=function(){var a=g.Hs("yt-remote-cast-receiver");
return a?a.friendlyName:null},yxa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},zxa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.So("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},qxa=function(){var a=0<=g.Lc.search(/ (CrMo|Chrome|CriOS)\//);
return g.dx||a},Axa=function(a,b){L7().init(a,b)},rxa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Gs("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Gs("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Gs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},sxa=function(a,b){K7(!0);
I7(!1);Axa(a,function(c){c?(wxa(!0),g.Uo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),txa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Gs("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},wxa=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.J=!1;this.H=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.J=!1;a.hasNext=!1;a.F=0;a.C=(0,g.G)();a.B=0;a.u=0;a.G=0;a.H=0;a.A=NaN;a.w=!1},T7=function(a){return a.ab()?((0,g.G)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.G)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.G)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Qb(a.o);b.hasPrevious=a.J;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.P.call(this);
this.o=0;this.A=a;this.C=[];this.B=new Nwa;this.w=this.u=null;this.H=(0,g.x)(this.zK,this);this.F=(0,g.x)(this.dm,this);this.G=(0,g.x)(this.yK,this);this.J=(0,g.x)(this.KK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Su,this),Bxa(this))):c=3;0!=c&&(b?this.Su(c):g.Lo((0,g.x)(function(){this.Su(c)},this),0));
var d=zxa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},Bxa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Sa(this.sM,b),this))},a)},Cxa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){Cxa(a);
a.A.setPlayerContextData(X7(b));Bxa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.dm(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.dm(a.w.media[0]))},Dxa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Tb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Tb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.P.call(this);
this.B=NaN;this.N=!1;this.G=this.F=this.H=this.J=NaN;this.V=[];this.A=this.C=this.w=this.Ta=this.o=null;this.U=a;this.V.push(g.Ip(window,"beforeunload",(0,g.x)(this.pF,this)));this.u=[];this.Ta=new R7;this.S=b.id;this.o=Exa(this,c);this.o.subscribe("handlerOpened",this.DK,this);this.o.subscribe("handlerClosed",this.AK,this);this.o.subscribe("handlerError",this.BK,this);this.o.subscribe("handlerMessage",this.CK,this);Rwa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ta.videoId;
g.Is()&&g.Gs("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Exa=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.P("proxyStateChange",b)},Fxa=function(a){a.B=g.Lo((0,g.x)(function(){g8("Connecting timeout");
this.lj(1)},a),2E4)},i8=function(a){g.No(a.B);
a.B=NaN},j8=function(a){g.No(a.J);
a.J=NaN},Gxa=function(a){k8(a);
a.H=g.Lo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.No(a.H);
a.H=NaN},Ixa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.jx()&&a.Ta.reset(),h8(a,1),l8(a,"getNowPlaying"),Hxa(a)):a.lj(1)},Jxa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ta.videoId&&(g.Mb(b.params)?a.Ta.o=null:a.Ta.o=b.params,a.P("remotePlayerChange"))},Kxa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ta.listId=b.params.listId||a.Ta.listId;W7(a.Ta,c,d);a.P("remoteQueueChange")},Mxa=function(a,b){b.params=b.params||{};
Kxa(a,b);Lxa(a,b);a.P("autoplayDismissed")},Lxa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Ta,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ta.playerState&&(c=-1E3);a.Ta.playerState=c;c=Number(b.params.loadedTime);a.Ta.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Ta.G=isNaN(c)?0:c;c=a.Ta;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Ta;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Ta.playerState?Gxa(a):k8(a);a.P("remotePlayerChange")},Nxa=function(a,b){if(-1E3!=
a.Ta.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ta.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Ta,isNaN(c)?0:c);a.P("remotePlayerChange")}},Oxa=function(a,b){var c="true"==b.params.muted;
a.Ta.volume=parseInt(b.params.volume,10);a.Ta.muted=c;a.P("remotePlayerChange")},Pxa=function(a,b){a.C=b.params.videoId;
a.P("nowAutoplaying",parseInt(b.params.timeout,10))},Qxa=function(a,b){var c="true"==b.params.hasNext;
a.Ta.J="true"==b.params.hasPrevious;a.Ta.hasNext=c;a.P("previousNextChange")},Hxa=function(a){g.No(a.G);
a.G=g.Lo((0,g.x)(a.lj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Lk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Dd=a;this.u=[];this.u.push(this.Dd.$_s("screenChange",(0,g.x)(this.xP,this)));this.u.push(this.Dd.$_s("onlineScreenChange",(0,g.x)(this.VL,this)))},Vxa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;Nva();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Vva()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",o8,void 0));Rxa();var c=p8();if(!c){var d=new v7(n8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);vxa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Lk(b)),s8.push(g.So("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.So("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.So("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.So("yt-remote-cast2-session-change",Sxa)),s8.push(g.So("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),yxa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.Bo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Lk(a)),Txa(a),c.start(),q8()||Uxa())},Xxa=function(){var a=Wxa();
N7()&&g.Hs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Wxa=function(){var a=p8().Dd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return Mva(a)},y8=function(){var a=Yxa();
!a&&N7()&&xxa()&&(a={key:"cast-selector-receiver",name:xxa()});return a},Yxa=function(){var a=Wxa(),b=w8();
b||(b=u8());return g.Za(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().me();return k6(b,a)},Sxa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Zxa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},$xa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Zxa("");g.Ia("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.Is();
if(!a)return null;var b=p8().me();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Zxa(a.id);var c=new f8(n8,a,v8());c.connect(b,$xa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Uxa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),yxa(),r8("Skipping connecting because no session screen found."))},Rxa=function(){var a=v8();
if(g.Mb(a)){a=o6();var b=g.Hs("yt-remote-session-name")||"",c=g.Hs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Txa=function(a){a?(g.Gs("yt-remote-session-app",a.app),g.Gs("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.w=new g.O(this);g.C(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.tL);this.w.L(b,"captionschanged",this.xK);this.w.L(b,"captionssettingschanged",this.gC);this.w.L(b,"videoplayerreset",this.mp);this.w.L(b,"mdxautoplaycancel",this.fE);this.S=this.w.L(b,"onVolumeChange",this.uA);this.G=!1;this.o=c;c.fa();c.subscribe("proxyStateChange",this.PA,this);c.subscribe("remotePlayerChange",this.jm,this);c.subscribe("remoteQueueChange",this.mp,this);c.subscribe("autoplayUpNext",
this.fA,this);c.subscribe("previousNextChange",this.LA,this);c.subscribe("nowAutoplaying",this.GA,this);c.subscribe("autoplayDismissed",this.eA,this);this.suggestion=null;this.H=new g.JC(64);this.A=new g.H(this.eC,500,this);g.C(this,this.A);this.C=new g.H(this.fC,1E3,this);g.C(this,this.C);this.N=new u6(this.YO,0,this);g.C(this,this.N);this.F={};this.V=new g.H(this.FC,1E3,this);g.C(this,this.V);this.J=new v6(this.kI,1E3,this);g.C(this,this.J);this.U=g.Ja;this.gC();this.mp();this.jm()},H8=function(a,
b){var c=a.B,d=a.u.getVideoData().lengthSeconds;
c.V=b||0;c.player.P("progresssync",b,d)},aya=function(a){H8(a,0);
a.A.stop();I8(a,new g.JC(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.Sb(c,b));a.o.VB(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.Af,zva(c));I8(a,new g.JC(1))},bya=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{tT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.PC(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.OS(a.u.app,d);a.H=b;cya(a.B,c,b)}},M8=function(){g.Q.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",O:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-confirm"],
W:"Confirm"}]}]}]});this.u=new g.LL(this,250);g.C(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.Q.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.NL()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.LL(this,250);g.C(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);dya(this,g.JK(a))},dya=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.FM("Error on $RECEIVER_NAME",c):b.ab()||g.V(b,4)?g.FM("Playing on $RECEIVER_NAME",c):g.FM("Connected to $RECEIVER_NAME",c);a.ka("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.dO.call(this,"Play on",0,a,b);
this.A=a;this.G={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.pL.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.S=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.JC(64);this.V=0;this.H=-1;this.C=null;if(!g.$y(this.player.M())){a=this.player;var b=g.dC(a);b&&(b=b.Sl())&&(b=new O8(a,b),g.C(this,b));b=new N8(a);g.C(this,b);g.cL(a,b.element,4);this.C=new M8;g.C(this,this.C);g.cL(a,this.C.element,4);this.N=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},cya=function(a,b,c){a.F=
c;
a.player.P("presentingplayerstatechange",new g.UC(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.M().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.N||!a.C);if(c?0:g.iz(a.player.M())||"WEB_EMBEDDED_PLAYER"==a.player.M().deviceParams.c)g.JK(a.player).ab()?a.player.pauseVideo():(a.G=(0,g.x)(a.RN,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.Zb(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=
c.videoId;if(!d&&!e||(2==a.player.getAppState()||1==a.player.getAppState())&&g.R(a.player.M().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.va(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Af,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=zva(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.Lk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().me(),(c=k6(c,b.key))&&A8(c,1))}},kwa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},eya={},Iva={aQ:"atp",HS:"ska",wS:"que",PR:"mus",GS:"sus",bR:"dsp",DS:"seq"};
d6.prototype.gi=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var r6,n6="",$va=Wva("loadCastFramework")||Wva("loadCastApplicationFramework"),uxa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(u6,g.A);g.h=u6.prototype;g.h.lF=function(a){this.A=arguments;this.o=!1;this.Ea?this.w=(0,g.G)()+this.Ed:this.Ea=g.Vf(this.B,this.Ed)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Fb.X.call(this)};
g.h.mF=function(){this.w?(this.Ea=g.Vf(this.B,this.w-(0,g.G)()),this.w=null):(this.Ea=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Ua(v6,g.A);g.h=v6.prototype;g.h.tj=!1;g.h.kl=0;g.h.Ea=null;g.h.sx=function(a){this.o=arguments;this.Ea||this.kl?this.tj=!0:w6(this)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null,this.tj=!1,this.o=[])};
g.h.pause=function(){this.kl++};
g.h.resume=function(){this.kl--;this.kl||!this.tj||this.Ea||(this.tj=!1,w6(this))};
g.h.X=function(){v6.Fb.X.call(this);this.stop()};
g.h.nF=function(){this.Ea=null;this.tj&&!this.kl&&(this.tj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},dwa(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ua(cwa,z6);S8=new cwa;g.h=A6.prototype;g.h.ti=null;g.h.gf=!1;g.h.xk=null;g.h.Pu=null;g.h.fk=null;g.h.uj=null;g.h.Ug=null;g.h.Jh=null;g.h.Pi=null;g.h.Nc=null;g.h.Km=0;g.h.mf=null;g.h.eq=null;g.h.jh=null;g.h.nl=-1;g.h.QB=!0;g.h.Zh=!1;g.h.Mr=0;g.h.xp=null;var iwa={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.dO=function(a){a=a.target;var b=this.xp;b&&3==R6(a)?b.sx():this.NC(a)};
g.h.NC=function(a){try{if(a==this.Nc)a:{var b=R6(this.Nc),c=this.Nc.C,d=this.Nc.getStatus();if(g.je&&!g.Nd(10)||g.le&&!g.Md("420+")){if(4>b)break a}else if(3>b||3==b&&!g.zh&&!T6(this.Nc))break a;this.Zh||4!=b||7==c||(8==c||0>=d?this.o.ff(3):this.o.ff(2));K6(this);var e=this.Nc.getStatus();this.nl=e;var f=T6(this.Nc);(this.gf=200==e)?(4==b&&G6(this),this.C?(jwa(this,b,f),g.zh&&this.gf&&3==b&&(this.A.ia(this.u,"tick",this.VN),this.u.start())):F6(this,f),this.gf&&!this.Zh&&(4==b?this.o.co(this):(this.gf=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.jh=3,E6(13)):(this.jh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Nc&&T6(this.Nc)}finally{}};
g.h.VN=function(){var a=R6(this.Nc),b=T6(this.Nc);this.Km<b.length&&(K6(this),jwa(this,a,b),this.gf&&4!=a&&C6(this))};
g.h.xN=function(a){J6((0,g.x)(this.wN,this,a),0)};
g.h.wN=function(a){this.Zh||(K6(this),F6(this,a),C6(this))};
g.h.YA=function(a){J6((0,g.x)(this.vN,this,a),0)};
g.h.vN=function(a){this.Zh||(G6(this),this.gf=a,this.o.co(this),this.o.ff(4))};
g.h.cancel=function(){this.Zh=!0;G6(this)};
g.h.FN=function(){this.xk=null;var a=(0,g.G)();0<=a-this.Pu?(2!=this.uj&&this.o.ff(3),G6(this),this.jh=2,E6(18),H6(this)):mwa(this,this.Pu-a)};
g.h.getLastError=function(){return this.jh};g.h=pwa.prototype;g.h.Kr=null;g.h.Yd=null;g.h.yp=!1;g.h.vx=null;g.h.Mn=null;g.h.xs=null;g.h.Lr=null;g.h.De=null;g.h.sg=-1;g.h.ll=null;g.h.Fk=null;g.h.connect=function(a){this.Lr=a;a=M6(this.o,null,this.Lr);E6(3);this.vx=(0,g.G)();var b=this.o.G;null!=b?(this.ll=b[0],(this.Fk=b[1])?(this.De=1,qwa(this)):(this.De=2,O6(this))):($5(a,"MODE","init"),this.Yd=new A6(this,void 0,void 0,void 0),this.Yd.ti=this.Kr,B6(this.Yd,a,!1,null,!0),this.De=0)};
g.h.gE=function(a){if(a)this.De=2,O6(this);else{E6(4);var b=this.o;b.yf=b.Yg.sg;$6(b,9)}a&&this.ff(2)};
g.h.Yq=function(a){return this.o.Yq(a)};
g.h.abort=function(){this.Yd&&(this.Yd.cancel(),this.Yd=null);this.sg=-1};
g.h.tx=function(){return!1};
g.h.QA=function(a,b){this.sg=a.nl;if(0==this.De)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.yf=this.sg;$6(c,2);return}this.ll=c[0];this.Fk=c[1]}else c=this.o,c.yf=this.sg,$6(c,2);else if(2==this.De)if(this.yp)E6(7),this.xs=(0,g.G)();else if("11111"==b){if(E6(6),this.yp=!0,this.Mn=(0,g.G)(),c=this.Mn-this.vx,!g.je||g.Nd(10)||500>c)this.sg=200,this.Yd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Mn=this.xs=(0,g.G)(),this.yp=!1};
g.h.co=function(){this.sg=this.Yd.nl;if(this.Yd.gf)0==this.De?this.Fk?(this.De=1,qwa(this)):(this.De=2,O6(this)):2==this.De&&((!g.je||g.Nd(10)?!this.yp:200>this.xs-this.Mn)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.De?E6(9):2==this.De&&E6(10);var a=this.o;this.Yd.getLastError();a.yf=this.sg;$6(a,2)}};
g.h.Am=function(){return this.o.Am()};
g.h.isActive=function(){return this.o.isActive()};
g.h.ff=function(a){this.o.ff(a)};g.Ua(P6,g.jf);var vwa=/^https?$/i,fya=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.U=!1;this.w=!0;this.o=this.S?ewa(this.S):ewa(S8);this.V=this.S?this.S.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.MA,this);try{b6(S6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));uwa(this,f);return}a=
c||"";var e=this.headers.clone();d&&Eva(d,function(f,k){e.set(k,f)});
d=g.Za(e.Ae(),swa);c=g.v.FormData&&a instanceof g.v.FormData;!g.bb(fya,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{xwa(this),0<this.F&&(this.N=rwa(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.N)),this.N?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.wx,this)):this.J=g.Vf(this.wx,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),uwa(this,f)}};
g.h.wx=function(){"undefined"!=typeof g.N1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Fb.X.call(this)};
g.h.MA=function(){this.fa()||(this.aa||this.G||this.B?wwa(this):this.uM())};
g.h.uM=function(){wwa(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Uk=null;g.h.Pd=null;g.h.qc=null;g.h.Jr=null;g.h.Pn=null;g.h.Sv=null;g.h.bo=null;g.h.Zl=0;g.h.SJ=0;g.h.Ad=null;g.h.dh=null;g.h.dg=null;g.h.ii=null;g.h.Yg=null;g.h.bq=null;g.h.Hj=-1;g.h.dy=-1;g.h.yf=-1;g.h.nj=0;g.h.gj=0;g.h.ai=8;var a7=new g.jf;g.Ua(zwa,g.Le);g.Ua(Awa,g.Le);g.Ua(Bwa,g.Le);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.Jr=b;this.Uk=c||{};d&&void 0!==e&&(this.Uk.OSID=d,this.Uk.OAID=e);this.C?(J6((0,g.x)(this.nw,this,a),100),Fwa(this)):this.nw(a)};
g.h.nw=function(a){this.Yg=new pwa(this);this.Yg.Kr=null;this.Yg.u=this.B;this.Yg.connect(a)};
g.h.tx=function(){return 0==this.o};
g.h.XA=function(a){this.dh=null;Iwa(this,a)};
g.h.WA=function(){this.dg=null;this.qc=new A6(this,this.w,"rpc",this.F);this.qc.ti=null;this.qc.Mr=0;var a=this.Sv.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.bq?"0":"1");Y5(a,"AID",this.Hj);V6(this,a);if(!g.je||g.Nd(10))Y5(a,"TYPE","xmlhttp"),B6(this.qc,a,!0,this.bo,!1);else{Y5(a,"TYPE","html");var b=this.qc,c=!!this.bo;b.uj=3;b.Ug=Z5(a.clone());lwa(b,c)}};
g.h.QA=function(a,b){if(0!=this.o&&(this.qc==a||this.Pd==a))if(this.yf=a.nl,this.Pd==a&&3==this.o)if(7<this.ai){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.dg){if(this.qc)if(this.qc.fk+3E3<this.Pd.fk)X6(this),this.qc.cancel(),this.qc=null;else break a;Z6(this);E6(19)}}else this.dy=c[1],0<this.dy-this.Hj&&37500>c[2]&&this.bq&&0==this.gj&&!this.ii&&(this.ii=J6((0,g.x)(this.tK,this),6E3));else $6(this,11)}else b!=eya.xQ.o&&$6(this,11);else if(this.qc==
a&&X6(this),!g.fc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Hj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.bo=e[2],e=e[3],null!=e?this.ai=e:this.ai=6,this.o=3,this.Ad&&this.Ad.iw(),this.Sv=M6(this,this.Am()?this.bo:null,this.Jr),Jwa(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Ad&&this.Ad.hw(e),this.gj=0)}}};
g.h.tK=function(){null!=this.ii&&(this.ii=null,this.qc.cancel(),this.qc=null,Z6(this),E6(20))};
g.h.co=function(a){if(this.qc==a){X6(this);this.qc=null;var b=2}else if(this.Pd==a)this.Pd=null,b=1;else return;this.yf=a.nl;if(0!=this.o)if(a.gf)1==b?(b=(0,g.G)()-a.fk,a7.dispatchEvent(new Awa(a7,a.Pi?a.Pi.length:0,b,this.nj)),W6(this),this.A.length=0):Jwa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.yf)){if(d=1==b)this.Pd||this.dh||1==this.o||2<=this.nj?d=!1:(this.dh=J6((0,g.x)(this.XA,this,a),Kwa(this,this.nj)),this.nj++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.FE=function(a){if(!g.bb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.PO=function(a){a?E6(2):(E6(1),Lwa(this,8))};
g.h.Yq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Z=!1;return a};
g.h.isActive=function(){return!!this.Ad&&this.Ad.isActive(this)};
g.h.ff=function(a){a7.dispatchEvent(new Bwa(a7,a))};
g.h.Am=function(){return!(!g.je||g.Nd(10))};
g.h=Mwa.prototype;g.h.iw=function(){};
g.h.hw=function(){};
g.h.gw=function(){};
g.h.Qq=function(){};
g.h.Rw=function(){return{}};
g.h.isActive=function(){return!0};g.h=Nwa.prototype;g.h.isEmpty=function(){return g.cb(this.o)&&g.cb(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.bb(this.o,a)||g.bb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Cqa)(b,a);0<=c?(g.eb(b,c),b=!0):b=!1;return b||g.fb(this.u,a)};
g.h.Id=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(b7,g.A);g.h=b7.prototype;g.h.nN=function(){this.Ed=Math.min(3E5,2*this.Ed);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Ed+15E3*Math.random();g.zn(this.o,a);this.u=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ed=5E3};g.Ua(c7,Mwa);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.Ah=function(a){return this.w.vi(a)};
g.h.P=function(a,b){return this.w.P.apply(this.w,arguments)};
g.h.dispose=function(){this.wb||(this.wb=!0,g.Je(this.w),Qwa(this),g.Je(this.u),this.u=null)};
g.h.fa=function(){return this.wb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Ad=null);d.Ad=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Hj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Sb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Gwa(this.o,c)};
g.h.iw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Gwa(this.o,a[b])}this.P("handlerOpened")};
g.h.gw=function(a){var b=2==a&&401==this.o.yf;4==a||b||this.u.start();this.P("handlerError",a)};
g.h.Qq=function(a){if(!this.u.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Rw=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.Sb(a,this.B);return a};
g.h.hw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Ewa(this.o)):this.P("handlerMessage",new Owa(a[0],a[1]))};
g.h.rO=function(){this.u.isActive();var a=this.o,b=0;a.qc&&b++;a.Pd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Ywa=(0,g.G)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ua(m7,g.P);m7.prototype.me=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.P);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ea)&&this.RC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ea)||(g.No(this.Ea),this.Ea=NaN)};
g.h.X=function(){this.stop();g.P.prototype.X.call(this)};
g.h.RC=function(){this.Ea=NaN;this.o=g.Iq(f7(this.C,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.vP,this),onError:(0,g.x)(this.uP,this),Vd:(0,g.x)(this.wP,this)})};
g.h.vP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.P("pairingComplete",new e6(c))};
g.h.uP=function(a){this.o=null;a.status&&404==a.status?this.u>=gya.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=gya[this.u],this.Ea=g.Lo((0,g.x)(this.RC,this),a),this.u++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.wP=function(){this.o=null;this.P("pairingFailed",Error("Server not responding"))};
var gya=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.P("screenChange");!g.Hs("yt-remote-lounge-token-expiration")&&bxa(this);g.No(this.u);this.u=g.Lo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Zwa(this,a);q7(this,!1);this.P("screenChange");b(a);a.token||bxa(this)};
g.h.remove=function(a,b){var c=o7(this);axa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Yp=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.X=function(){g.No(this.u);p7.Fb.X.call(this)};
g.h.xF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.wF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.P);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Hs("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?u7(this):(this.A=(0,g.G)()+3E5,g.Gs("yt-remote-fast-check-period",this.A),this.gu())};
g.h.isEmpty=function(){return g.Mb(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Ab(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.No(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.P.prototype.X.call(this)};
g.h.gu=function(){g.No(this.w);this.w=NaN;this.u&&this.u.abort();var a=exa(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Gb(a).join(",")},(0,g.x)(this.RM,this,a),(0,g.x)(this.QM,this))}else t7(this,{}),u7(this)};
g.h.RM=function(a,b){this.u=null;var c=g.Gb(exa(this));if(g.tb(c,g.Gb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Tb("Changing Screen set during request."),this.gu()};
g.h.QM=function(a){this.Tb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Tb=function(a){i7("OnlineScreenService",a)};g.Ua(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.P("screenChange"),this.u.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.Yp=function(a,b,c,d){this.w.contains(a)?this.w.Yp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.me=function(a){return a?this.o:g.ib(this.o,(0,g.we)(this.A,function(b){return!this.contains(b)},this))};
g.h.SC=function(){return(0,g.we)(this.me(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.TC=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Je(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Je(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.yP=function(a,b,c,d){g.Iq(f7(this.C,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||ixa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);ixa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Vd:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.Je(this.w);g.Je(this.u);v7.Fb.X.call(this)};
g.h.GF=function(){jxa(this);this.P("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ua(y7,g.P);g.h=y7.prototype;g.h.lp=function(a){this.w=a;this.P("sessionScreen",this.w)};
g.h.pe=function(a){this.fa()||(a&&z7(this,""+a),this.w=null,this.P("sessionScreen",null))};
g.h.info=function(a){i7(this.V,a)};
g.h.VC=function(){return null};
g.h.pu=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.pu("");y7.Fb.X.call(this)};g.Ua(A7,y7);g.h=A7.prototype;g.h.ou=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);lxa(this)};
g.h.Ij=function(a){this.info("launchWithParams no-op for Cast: "+g.Lk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.pe()},this),(0,g.x)(function(){this.pe(Error("Failed to stop receiver app."))},this)):this.pe(Error("Stopping cast device witout session."))};
g.h.pu=g.Ja;g.h.X=function(){this.info("disposeInternal");g.No(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Fb.X.call(this)};
g.h.NN=function(a,b){if(!this.fa())if(b){var c=x6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Lk(c));switch(d){case "mdxSessionStatus":kxa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.lx=function(a,b,c,d){hxa(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Lo((0,g.x)(this.lx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.VC=function(){return this.o};
g.h.zP=function(a){this.fa()||a||(z7(this,"Cast session died."),this.pe())};g.Ua(B7,y7);g.h=B7.prototype;g.h.ou=function(a){this.A=a;this.A.addUpdateListener(this.N)};
g.h.Ij=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ja;g.No(this.C);this.A?this.A.stop((0,g.x)(this.pe,this,null),(0,g.x)(this.pe,this,"Failed to stop DIAL device.")):this.pe()};
g.h.X=function(){this.o();this.o=g.Ja;g.No(this.C);this.A&&this.A.removeUpdateListener(this.N);this.A=null;B7.Fb.X.call(this)};
g.h.CP=function(a){this.fa()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.pe())};
g.h.Ur=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,nxa(this));a(b);mxa(this)}else this.F=(0,g.x)(function(){g.No(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,nxa(this));a(c);mxa(this)},this),this.C=g.Lo((0,g.x)(function(){this.F()},this),100)};
g.h.ZF=function(a,b,c){hxa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.lp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Ur(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Ur(b,c)},this))};g.Ua(C7,y7);C7.prototype.stop=function(){this.pe()};
C7.prototype.ou=g.Ja;C7.prototype.Ij=function(){g.No(this.o);this.o=NaN;var a=k6(this.H.me(),this.u.label);a?this.lp(a):this.pe(Error("No such screen"))};
C7.prototype.X=function(){g.No(this.o);this.o=NaN;C7.Fb.X.call(this)};g.Ua(D7,g.P);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.zM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.TA,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.RK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.A),Vwa(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.UC,this)),this.w=pxa(this),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(k){this.Tb("Failed to set initial custom receivers: "+g.Lk(k))},this)),this.P("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Tb("Failed to initialize API: "+g.Lk(k));
b(!1)},this))};
g.h.zO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.me(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=oxa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ja,(0,g.x)(function(e){this.Tb("Failed to set initial custom receivers: "+g.Lk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.pu(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.AO=function(a){this.fa()?this.Tb("Setting connection data on disposed cast v2"):this.o?this.o.Ij(a):this.Tb("Setting connection data without a session")};
g.h.BP=function(){this.fa()?this.Tb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.TA,this),(0,g.x)(this.VM,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.UC,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Swa,b=g.w("yt.mdx.remote.debug.handlers_");g.fb(b||[],a);g.Je(this.o);D7.Fb.X.call(this)};
g.h.Tb=function(a){i7("Controller",a)};
g.h.VA=function(a,b){this.o==a&&(b||G7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.vM=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.P("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Tb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Tb("Stopping receiver w/o session: "+a.friendlyName)}else this.Tb("onReceiverAction_ called without receiver.")};
g.h.RK=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Tb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Tb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Tb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.ZF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Ur,b))};
g.h.TA=function(a){if(!this.fa()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Tb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.me(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Je(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.VA,this,this.o)),this.o.Ij(null));this.o.ou(a)}}};
g.h.AP=function(){return this.o?this.o.VC():null};
g.h.VM=function(a){this.fa()||(this.Tb("Failed to estabilish a session: "+g.Lk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.zM=function(a){E7("Receiver availability updated: "+a);if(!this.fa()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.P("yt-remote-cast2-availability-change",F7(this))}};
g.h.UC=function(){this.fa()||(this.w=pxa(this),E7("Updating custom receivers: "+g.Lk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(){this.Tb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.AO;D7.prototype.setConnectedScreenStatus=D7.prototype.zO;D7.prototype.stopSession=D7.prototype.BP;D7.prototype.getCastSession=D7.prototype.AP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.h=R7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.J=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.A=a.liveIngestionTime,this.w=!isNaN(this.A))};
g.h.ab=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.w?this.G+T7(this):this.G};
g.h.clone=function(){return new R7(X7(this))};g.r(Z7,g.P);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.ab()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.P("remotePlayerChange")}else a8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.P("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Tb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Tb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Sa(this.setVolume,a,b))};
g.h.VB=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Lk(b.style),g.Sb(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Sa(this.VB,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Lk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.QC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Sa(this.QC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Sa(this.nextVideo,a,b))};
g.h.yw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.yw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.P("proxyStateChange",a,this.o)}g.P.prototype.dispose.call(this)};
g.h.X=function(){Cxa(this);this.A=null;this.B.clear();Y7(this,null);g.P.prototype.X.call(this)};
g.h.Su=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.cb(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.sM=function(a,b){this.P(a,b)};
g.h.zK=function(a){if(!a)this.dm(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.dm=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),Dxa(this),this.P("remotePlayerChange")};
g.h.yK=function(a){a?(Dxa(this),this.P("remotePlayerChange")):this.dm(null)};
g.h.KK=function(){var a=zxa();a&&Y7(this,a)};
g.h.Tb=function(a){i7("CP",a)};g.r(f8,g.P);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Ta.listId=c);this.Ta.videoId=d;this.Ta.index=k||0;this.Ta.state=3;U7(this.Ta,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Lk(l));this.o.connect({method:"setPlaylist",
params:g.Lk(l)},a,Qva())}else g8("Connecting without params"),this.o.connect({},a,Qva());Fxa(this)};
g.h.dispose=function(){this.fa()||(this.P("beforeDispose"),h8(this,3));g.P.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.No(this.F);this.F=NaN;g.No(this.G);this.G=NaN;this.w=null;g.Jp(this.V);this.V.length=0;this.o.dispose();g.P.prototype.X.call(this);this.A=this.C=this.u=this.Ta=this.o=null};
g.h.pF=function(){this.lj(2)};
g.h.DK=function(){g8("Channel opened");this.N&&(this.N=!1,j8(this),this.J=g.Lo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.lj(1)},this),15E3));
Uva(Pwa(this.o),this.S)};
g.h.AK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.BK=function(a){q6();isNaN(this.bl())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,g8("Channel error: "+a+" with reconnection in "+this.bl()+" ms"),h8(this,2))};
g.h.CK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Lk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.Ec)(a,function(c){return new d6(c)});
a=!!g.Za(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Ixa(this,a);break;case "loungeScreenDisconnected":g.gb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Ixa(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.Za(this.u,function(c){return b?c.id==b.id:!1})||Ava(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.gb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Kxa(this,a);break;case "nowPlaying":Mxa(this,a);break;case "onStateChange":Lxa(this,a);break;case "onAdStateChange":Nxa(this,a);break;case "onVolumeChanged":Oxa(this,a);break;case "onSubtitlesTrackChanged":Jxa(this,a);break;case "nowAutoplaying":Pxa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.P("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Qxa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.nO=function(){if(this.w){var a=this.w;this.w=null;this.Ta.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.eF=function(){var a=3;this.fa()||(a=0,isNaN(this.bl())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.lj=function(a){g8("Disconnecting with "+a);i8(this);this.P("beforeDisconnect",a);1==a&&q6();Qwa(this.o,a);this.dispose()};
g.h.dF=function(){var a=this.Ta;this.w&&(a=this.Ta.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.BO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Ta.videoId&&(this.w=b.videoId,g.No(this.F),this.F=g.Lo((0,g.x)(this.nO,this),5E3));var c=[];this.Ta.listId==b.listId&&this.Ta.videoId==b.videoId&&this.Ta.index==b.index||c.push("remoteQueueChange");this.Ta.playerState==b.playerState&&this.Ta.volume==b.volume&&this.Ta.muted==b.muted&&V7(this.Ta)==V7(b)&&g.Lk(this.Ta.o)==g.Lk(b.o)||c.push("remotePlayerChange");this.Ta.reset(a);(0,g.y)(c,function(d){this.P(d)},this)};
g.h.jx=function(){var a=this.o.C.id,b=g.Za(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.bl=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.G)():NaN};
g.h.SE=function(){return this.A||"UNSUPPORTED"};
g.h.TE=function(){return this.C||""};
g.h.tP=function(){if(!isNaN(this.bl())){var a=this.o.u;g.An(a.o);a.start()}};
g.h.wO=function(a,b){l8(this,a,b);Hxa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.Ah;f8.prototype.getProxyState=f8.prototype.eF;f8.prototype.disconnect=f8.prototype.lj;f8.prototype.getPlayerContextData=f8.prototype.dF;f8.prototype.setPlayerContextData=f8.prototype.BO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.jx;f8.prototype.getReconnectTimeout=f8.prototype.bl;f8.prototype.getAutoplayMode=f8.prototype.SE;f8.prototype.getAutoplayVideoId=f8.prototype.TE;f8.prototype.reconnect=f8.prototype.tP;
f8.prototype.sendMessage=f8.prototype.wO;g.r(m8,m7);g.h=m8.prototype;g.h.me=function(a){return this.Dd.$_gs(a)};
g.h.contains=function(a){return!!this.Dd.$_c(a)};
g.h.get=function(a){return this.Dd.$_g(a)};
g.h.start=function(){this.Dd.$_st()};
g.h.add=function(a,b,c){this.Dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Dd.$_r(a,b,c)};
g.h.Yp=function(a,b,c,d){this.Dd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.Dd.$_ubk(this.u[a]);this.u.length=0;this.Dd=null;m7.prototype.X.call(this)};
g.h.xP=function(){this.P("screenChange")};
g.h.VL=function(){this.P("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.yP;v7.prototype.$_gsppc=v7.prototype.TC;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Yp;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.me;v7.prototype.$_gos=v7.prototype.SC;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.Ah;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.X=function(){g.A.prototype.X.call(this);this.A.stop();this.C.stop();this.N.stop();this.U();this.o.unsubscribe("proxyStateChange",this.PA,this);this.o.unsubscribe("remotePlayerChange",this.jm,this);this.o.unsubscribe("remoteQueueChange",this.mp,this);this.o.unsubscribe("autoplayUpNext",this.fA,this);this.o.unsubscribe("previousNextChange",this.LA,this);this.o.unsubscribe("nowAutoplaying",this.GA,this);this.o.unsubscribe("autoplayDismissed",this.eA,this);this.o=this.B=null};
g.h.ez=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":$7(this.o).ab()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.sx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.xK=function(a){this.N.lF(a)};
g.h.YO=function(a){this.ez("control_subtitles_set_track",g.Mb(a)?null:a)};
g.h.gC=function(){var a=this.u.getOption("captions","track");g.Mb(a)||K8(this,a)};
g.h.uA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.jm,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.V.start();this.o.subscribe("remotePlayerChange",this.jm,this)}};
g.h.tL=function(){g.Mb(this.F)||bya(this,this.F);this.G=!1};
g.h.PA=function(a,b){this.C.stop();2==b&&this.fC()};
g.h.jm=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.JC(8));this.eC();break;case 1085:case 3:I8(this,new g.JC(9));break;case 1083:case 0:I8(this,new g.JC(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.JC(4));break;case 2:I8(this,new g.JC(4));H8(this,V7(a));
break;case -1:I8(this,new g.JC(64));break;case -1E3:I8(this,new g.JC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,bya(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.V.isActive()||this.FC()}else aya(this)};
g.h.LA=function(){this.u.P("mdxpreviousnextchange")};
g.h.mp=function(){J8(this)||aya(this)};
g.h.fE=function(){this.o.yw()};
g.h.fA=function(){};
g.h.GA=function(a){isNaN(a)||this.u.P("mdxnowautoplaying",a)};
g.h.eA=function(){this.u.P("mdxautoplaycanceled")};
g.h.kI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.FC=function(){if(J8(this)){var a=$7(this.o);this.w.Xa(this.S);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.S=this.w.L(this.u,"onVolumeChange",this.uA)}};
g.h.eC=function(){this.A.stop();if(!this.o.fa()){var a=$7(this.o);a.ab()&&I8(this,new g.JC(8));H8(this,V7(a));this.A.start()}};
g.h.fC=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.Q);M8.prototype.Zb=function(){this.u.show()};
M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.Q);N8.prototype.A=function(a){dya(this,a.state)};g.r(O8,g.dO);O8.prototype.J=function(){var a=this.A.getOption("remote","receivers");a&&1<a.length&&!this.A.getOption("remote","quickCast")?(this.G=g.vb(a,this.B,this),g.fO(this,(0,g.Ec)(a,this.B)),a=this.A.getOption("remote","currentReceiver"),this.Je(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.cf=function(a){return"cast-selector-receiver"==a?"Cast...":this.G[a].name};
O8.prototype.hd=function(a){g.dO.prototype.hd.call(this,a);this.A.setOption("remote","currentReceiver",this.G[a]);this.u.bb()};g.r(P8,g.pL);g.h=P8.prototype;
g.h.create=function(){Vxa(g.Ry(this.player.M()));this.A.push(g.So("yt-remote-before-disconnect",this.uK,this));this.A.push(g.So("yt-remote-connection-change",this.AM,this));this.A.push(g.So("yt-remote-receiver-availability-change",this.NA,this));this.A.push(g.So("yt-remote-auto-connect",this.yM,this));this.A.push(g.So("yt-remote-receiver-resumed",this.xM,this));this.A.push(g.So("mdx-privacy-popup-confirm",this.ZN,this));this.A.push(g.So("mdx-privacy-popup-cancel",this.YN,this));this.NA()};
g.h.load=function(){this.player.cancelPlayback();g.pL.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=$xa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.V=a||0,this.player.P("progresssync",a,void 0));cya(this,this.F,this.F);g.VS(this.player.app,6)};
g.h.unload=function(){this.player.P("mdxautoplaycanceled");this.w=this.u;g.Ke(this.B,this.o);this.o=this.B=null;g.pL.prototype.unload.call(this);g.VS(this.player.app,5);Q8(this)};
g.h.X=function(){g.To(this.A);g.pL.prototype.X.call(this)};
g.h.Kl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.ez.apply(this.B,[a].concat(g.na(c)))};
g.h.getAdState=function(){return this.H};
g.h.gF=function(){return this.loaded?this.B.suggestion:null};
g.h.zy=function(){return this.o?$7(this.o).J:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.V};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.M().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Rc():!a.isAdPlaying()&&this.player.Rc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+T7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.BG=function(){this.o&&this.o.QC()};
g.h.uK=function(a){1==a&&(this.S=this.o?$7(this.o):null)};
g.h.AM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.S=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.Je(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.S)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.P("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.NA=function(){this.J=[this.u].concat(Xxa());var a=y8()||this.u;R8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.RN=function(a){!this.N&&g.WC(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.yM=function(){var a=y8();R8(this,a)};
g.h.xM=function(){this.w=y8()};
g.h.ZN=function(){this.N=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.YN=function(){this.N=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Pc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.CG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.EL.remote=P8;})(_yt_player);
