define("app/ui/list_members_dashboard",["module","require","exports","core/component","app/ui/with_user_actions","app/ui/with_item_actions"],function(module, require, exports) {
function listMembersDashboard(){this.defaultAttrs({itemType:"user",followCardSelector:".dashboard .follow-card"}),this.handleNewListMembers=function(a,b){b.newest_members_html&&this.$node.html(b.newest_members_html),b.follow_card_html&&$(this.attr.followCardSelector).html(b.follow_card_html)},this.after("initialize",function(){this.on(document,"dataGotNewListMembers",this.handleNewListMembers)})}var defineComponent=require("core/component"),withUserActions=require("app/ui/with_user_actions"),withItemActions=require("app/ui/with_item_actions");module.exports=defineComponent(listMembersDashboard,withUserActions,withItemActions)
});
define("app/data/list_members_dashboard",["module","require","exports","core/component","app/data/with_data"],function(module, require, exports) {
function listMembersDashboardData(){this.getNewestMembers=function(a,b){b.sourceEventData.listId==this.attr.listId&&this.get({url:this.attr.endPoint,data:{},eventData:b,success:"dataGotNewListMembers",error:"dataFailedToGetNewListMembers"})},this.after("initialize",function(){this.attr.listId=this.attr.list_id,this.attr.endPoint=this.attr.newest_members_url,this.on(document,"dataDidAddUserToList dataDidRemoveUserFromList",this.getNewestMembers)})}var defineComponent=require("core/component"),withData=require("app/data/with_data");module.exports=defineComponent(listMembersDashboardData,withData)
});
define("app/boot/list_permalink",["module","require","exports","app/boot/app","app/boot/logged_out","app/ui/profile/list_create_button","app/ui/list_members_dashboard","app/data/list_members_dashboard","app/ui/list_actions","app/data/list_actions","app/data/list_actions_scribe"],function(module, require, exports) {
function initialize(a){bootApp(a),loggedOutBoot(a),ListMembersDashboard.attachTo(".dashboard .newest-members-module",a),ListMembersDashboardData.attachTo(document,a),ListActions.attachTo(document,a,{redirectToListPermalinkOnEdit:!0,rerenderListItem:!0}),ListActionsData.attachTo(document,a),ListActionsScribe.attachTo(document,a,{scribeContext:{component:"list_follow_card"}}),ListCreateButton.attachTo(".dashboard")}var bootApp=require("app/boot/app"),loggedOutBoot=require("app/boot/logged_out"),ListCreateButton=require("app/ui/profile/list_create_button"),ListMembersDashboard=require("app/ui/list_members_dashboard"),ListMembersDashboardData=require("app/data/list_members_dashboard"),ListActions=require("app/ui/list_actions"),ListActionsData=require("app/data/list_actions"),ListActionsScribe=require("app/data/list_actions_scribe");module.exports=initialize
});
define("app/pages/list/permalink_tweets",["module","require","exports","app/boot/list_permalink","app/boot/tweet_timeline","app/ui/dynamic_card_watcher"],function(module, require, exports) {
var listPermalinkBoot=require("app/boot/list_permalink"),tweetTimelineBoot=require("app/boot/tweet_timeline"),DynamicCardWatcher=require("app/ui/dynamic_card_watcher");module.exports=function(b){listPermalinkBoot(b),DynamicCardWatcher.attachTo(document,{containerSelector:"#timeline",viewportThreshold:200}),tweetTimelineBoot(b,b.timeline_url,"swift_list_tweets_timeline","tweet","tweet")}
});
define("app/ui/timelines/user_timeline",["module","require","exports","app/ui/timelines/base_timeline","app/ui/timelines/with_old_items","app/ui/timelines/with_min_max_pagination","app/ui/with_item_actions","app/ui/with_user_actions","app/ui/with_stream_users","app/ui/timelines/with_excluded_ids_pagination"],function(module, require, exports) {
function userTimeline(){this.defaultAttrs({itemType:"user"})}var BaseTimeline=require("app/ui/timelines/base_timeline"),withOldItems=require("app/ui/timelines/with_old_items"),withMinMaxPagination=require("app/ui/timelines/with_min_max_pagination"),withItemActions=require("app/ui/with_item_actions"),withUserActions=require("app/ui/with_user_actions"),withStreamUsers=require("app/ui/with_stream_users"),withExcludedIdsPagination=require("app/ui/timelines/with_excluded_ids_pagination");module.exports=BaseTimeline.mixin(userTimeline,withOldItems,withMinMaxPagination,withItemActions,withUserActions,withStreamUsers,withExcludedIdsPagination)
});
define("app/boot/user_timeline",["module","require","exports","app/boot/timeline","app/ui/timelines/user_timeline","app/data/tweet_actions","core/utils"],function(module, require, exports) {
function initialize(a,b,c,d){var e=utils.merge(a,{endpoint:b,itemType:c,eventData:{scribeContext:{component:d}}});timelineBoot(e),UserTimeline.attachTo("#timeline",e),TweetActionsData.attachTo(document,e)}var timelineBoot=require("app/boot/timeline"),UserTimeline=require("app/ui/timelines/user_timeline"),TweetActionsData=require("app/data/tweet_actions"),utils=require("core/utils");module.exports=initialize
});
define("app/pages/list/permalink_users",["module","require","exports","app/boot/list_permalink","app/boot/user_timeline"],function(module, require, exports) {
var listPermalinkBoot=require("app/boot/list_permalink"),userTimelineBoot=require("app/boot/user_timeline");module.exports=function(b){listPermalinkBoot(b),userTimelineBoot(b,b.timeline_url,"user","user")}
});